import { approveDraft } from "@/lib/domain/personalization/drafts";
import { enqueueDraftGeneration, MAX_BULK_DRAFTS, type DraftBatchResult } from "@/lib/domain/personalization/service";
import { resolveAudience } from "./audience";
import { loadCampaign, loadCurrentDrafts } from "./repository";
import { isStructureEditable } from "./state-machine";
import type { Actor } from "./service";
import { AppError } from "@/lib/api/errors";

/**
 * The builder's Personalization step reuses Phase 3 wholesale: drafts are generated by the `personalization` job and
 * approved through the same draft lifecycle (which re-validates against today's evidence). Nothing here writes a draft.
 */

async function audienceDrafts(actor: Actor, campaignId: number) {
  const c = await loadCampaign(actor.workspaceId, campaignId);
  const r = await resolveAudience(actor.workspaceId, c.audience, { excludeCampaignId: campaignId });
  const leads = r.eligible.slice(0, c.totalLimit ?? r.eligible.length);
  const drafts = await loadCurrentDrafts(actor.workspaceId, leads.map((l) => l.id));
  return { c, leads, drafts };
}

/** Queues drafts for audience leads that have none (or a rejected one), at most MAX_BULK_DRAFTS per click. */
export async function generateAudienceDrafts(actor: Actor & { userId: number }, campaignId: number): Promise<DraftBatchResult & { remaining: number }> {
  const { c, leads, drafts } = await audienceDrafts(actor, campaignId);
  if (!isStructureEditable(c.status)) throw new AppError("CONFLICT", "Drafts can only be generated before the campaign is approved.");
  const todo = leads.filter((l) => {
    const d = drafts.get(l.id);
    return !d || d.status === "rejected";
  });
  if (todo.length === 0) throw new AppError("CONFLICT", "Every lead in this audience already has a draft.");
  const batch = todo.slice(0, MAX_BULK_DRAFTS).map((l) => l.id);
  const res = await enqueueDraftGeneration(actor, batch, { tone: c.tone });
  return { ...res, remaining: todo.length - batch.length };
}

/**
 * Approves every audience draft that passed all checks (status `draft`, no errors). Each approval goes through
 * `approveDraft`, which re-checks the draft against today's evidence and refuses anything that no longer passes.
 */
export async function approveCleanAudienceDrafts(actor: Actor & { userId: number }, campaignId: number): Promise<{ approved: number; refused: { leadId: number; message: string }[] }> {
  const { leads, drafts } = await audienceDrafts(actor, campaignId);
  let approved = 0;
  const refused: { leadId: number; message: string }[] = [];
  for (const l of leads) {
    const d = drafts.get(l.id);
    if (!d || d.status !== "draft") continue;
    try {
      await approveDraft(actor, d.draftId);
      approved++;
    } catch (err) {
      refused.push({ leadId: l.id, message: err instanceof Error ? err.message : "Could not approve" });
    }
  }
  return { approved, refused };
}
