// Regenerates chrome-extension/ui/icons.js from the same Phosphor icon set the dashboard uses, so the extension's
// icons are literally the dashboard's icons (not lookalikes).
//
//   node scripts/extension-icons.mjs
//
// The extension has no build step, so the SVG markup is generated once and committed.
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as Ph from "@phosphor-icons/react/ssr";
import { writeFileSync } from "node:fs";

const NAMES = [
  "UserPlus", "PlugsConnected", "LinkBreak", "CheckCircle", "WarningCircle", "ArrowSquareOut", "MagnifyingGlass", "SignOut", "GearSix",
  "UsersThree", "Buildings", "EnvelopeSimple", "CircleNotch", "X", "CaretRight", "ShieldCheck", "MagicWand", "Globe", "Info", "Trash",
  "ArrowClockwise", "Lightning", "IdentificationCard", "Link", "Prohibit", "ClockCounterClockwise",
];

// Structured shapes, not markup: LinkedIn enforces Trusted Types, which forbids parsing an HTML/SVG *string* into the
// page (innerHTML, DOMParser…). The extension builds nodes with createElementNS from this data instead.
function shapes(svg) {
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  const list = [];
  for (const m of inner.matchAll(/<(\w+)([^>]*?)(?:\/>|>\s*<\/\1>)/g)) {
    const attrs = {};
    for (const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g)) attrs[a[1]] = a[2];
    list.push([m[1], attrs]);
  }
  if (list.length === 0) throw new Error(`Could not read shapes from: ${inner.slice(0, 80)}`);
  return list;
}

const out = {};
for (const name of NAMES) {
  const C = Ph[name];
  if (!C) throw new Error(`Phosphor has no icon named ${name}`);
  const duotone = renderToStaticMarkup(createElement(C, { weight: "duotone" }));
  const bold = renderToStaticMarkup(createElement(C, { weight: "bold" }));
  const fill = renderToStaticMarkup(createElement(C, { weight: "fill" }));
  out[name] = { duotone: shapes(duotone), bold: shapes(bold), fill: shapes(fill) };
}

const body = `// GENERATED by scripts/extension-icons.mjs from @phosphor-icons/react — do not edit by hand.
// Each entry lists the shapes ([tag, attrs]) of a 256×256 Phosphor SVG in three weights.
export const ICONS = ${JSON.stringify(out, null, 1)};
`;
writeFileSync(new URL("../chrome-extension/ui/icons.js", import.meta.url), body);
console.log(`wrote ${NAMES.length} icons`);
